spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yangdada666123456/tensquare-config
          username: 14781816651
          password: yangdada666..
          skip-ssl-validation: true
  rabbitmq:
    host: 192.168.128.133
#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 12000